NumPy is the fundamental base for scientific computing in python. It contains:
N-dimensional array objects vectorization of functions Tools for integrating C/C++ and fortran code linear algebra, fourier transformation, and random number tools.
Now, NumPy is the basis for a lot of other packages like scikit-learn, scipy, pandas, among other packages but provides a lot of power in and of itself and they keep numpy pretty abstract however it provides a strong foundation for us to learn some of the operations and concepts we’ll be applying later on.
Let’s go ahead and get started.

In [2]:
import sys 

In [3]:
print (sys.version)

2.7.11 |Anaconda 4.0.0 (x86_64)| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)]


The sys module provides information about constants, functions and methods of the Python interpreter. dir(system) gives a summary of the available constants, functions and methods. Another possibility is the help() function. Using help(sys) provides valuable detail information. 

In [4]:
import numpy as np

In [5]:
range (1)

[0]

In [6]:
range (10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
npa.mean(10)

NameError: name 'npa' is not defined

In [9]:
npa=np.arange(10)

In [10]:
npa.mean

<function mean>

In [11]:
npa.mean()

4.5

In [12]:
npa.max()

9

In [13]:
[x*x for x in npa]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

You’ll see that we can do things like list comprehensions on arrays however this is not the recommended method which would be to vectorize our operation.
Vectorization in simplest terms allows you to apply a function to an entire array instead of doing it value by value - similar to what we were doing with map and filter in the previous videos. This typically makes things much more concise and readable. Not necessarily in the trivial examples like we’re doing in these initial videos but when we move along into more complicated analysis the speed improvements are significant.

In [14]:
npa**2


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [15]:
npa=np.arange(20)

In [16]:
npa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

list comprehension performance is slow

In [17]:
[x for x in npa if x%2==0]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [18]:
list(filter(lambda x:x%2==0,npa))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

list 里面是个function，npa是说明sequence

In [19]:
np2=np.arange(20000)

In [20]:
%timeit(x for x in np2 if x%2==0)

The slowest run took 5.32 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 583 ns per loop


In [22]:
%timeit np2(np2%2==0)

TypeError: 'numpy.ndarray' object is not callable

In [23]:
%timeit np2[np2%2==0]

1000 loops, best of 3: 381 µs per loop


In [24]:
np2[np2%2==0]

array([    0,     2,     4, ..., 19994, 19996, 19998])

raw python处理的很慢

numpy arrow is more efficient than raw python

In [25]:
npa[npa>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [26]:
print type(npa)

<type 'numpy.ndarray'>


In [27]:
np.array([1,0,0,2,3])

array([1, 0, 0, 2, 3])

In [28]:
np.array([true,2,2.0])

NameError: name 'true' is not defined

In [30]:
np.array([True,2,2.0]).dtype


dtype('float64')

In [31]:
 True==1
    

True

shape 指的是dimention


In [33]:
def new_func(numb):
    if numb<10:
        return numb**3
    else:
        return numb**2

In [34]:
num_func(10)

NameError: name 'num_func' is not defined

In [35]:
new_func(10)

100

In [36]:
print(npa)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [37]:
new_func(npa)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [38]:
vect_new_func=np.vectorize(new_func)

In [39]:
type(vect_new_func)

numpy.lib.function_base.vectorize

In [40]:
vect_new_func(npa)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [41]:
import pandas as pd

In [42]:
pd.Index

pandas.indexes.base.Index

In [43]:
pd.Series

pandas.core.series.Series

In [44]:
pd.DataFrame

pandas.core.frame.DataFrame

In [45]:
letters=pd.DataFrame([lowercase, uppercase, range(26)])

NameError: name 'lowercase' is not defined

In [46]:
lcase=string.ascii_lowercase

NameError: name 'string' is not defined

In [47]:
import string

In [48]:
lcase=string.ascii_lowercase

In [49]:
ucase=string.ascii_uppercase

In [50]:
print lcase,ucase

abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ


In [51]:
lcase=list(lcase)

In [52]:
print (lcase)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [53]:
print lcase

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [54]:
series_ex.index=lcase

NameError: name 'series_ex' is not defined

In [ ]:
letter